DELETE http://localhost:3001/api/blogs/66d2342338f7bad930df6363
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2NmM0ZmM3ZDgwY2JiNjRlNmRhNGRjNGQiLCJpYXQiOjE3MjU0NzA3NjEsImV4cCI6MTcyNTQ3NDM2MX0.jScIrw3cO_YtcEVBrHB42NfXhEqzeXZ8T_X-9CqIxxk
Content-Type: application/json
